image: node:alpine

cache:
  paths:
    - node_modules/
    - package-lock.json

build:
  stage: build
  artifacts:
    paths:
      - public/
  before_script:
    - npm update -g
  script:
    - npm install
    - npm run production

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script: echo "OK"
  
